import { RoomType } from "@/types";

export const PREFERRED_TASKS: Record<RoomType, string[]> = {
  Bedroom: [
    "Change bed sheets",
    "Clean under bed",
    "Clean bedside table",
    "Tidy up wardrobe",
    "Clean TV",
    "Wash pillows",
    "Wash blankets",
    "Wash mattress pad",
    "Organize drawers",
    "Dust surfaces",
  ],
  "Child's room": [
    "Change bed sheets",
    "Clean under bed",
    "Tidy up wardrobe",
    "Organize drawers",
    "Dust surfaces",
    "Clean TV",
    "Wash pillows",
    "Wash blankets",
  ],
  Bathroom: [
    "Clean toilet",
    "Clean shower",
    "Clean sink",
    "Mop floor",
    "Clean mirror",
    "Wash bath mat",
    "Clean cabinets",
  ],
  Toilet: [
    "Clean toilet",
    "Clean sink",
    "Mop floor",
    "Clean mirror",
    "Clean cabinets",
  ],
  "Dining room": [
    "Clean table",
    "Clean chairs",
    "Vacuum floor",
    "Dust surfaces",
    "Clean windows",
  ],
  Entrance: [
    "Sweep floor",
    "Clean door mat",
    "Organize shoes",
    "Clean windows",
    "Dust surfaces",
  ],
  "Dressing room": [
    "Organize clothes",
    "Clean mirrors",
    "Vacuum floor",
    "Dust surfaces",
    "Clean drawers",
  ],
  Kitchen: [
    "Clean counters",
    "Clean stove",
    "Clean sink",
    "Mop floor",
    "Clean cabinets",
    "Clean appliances",
    "Clean fridge",
    "Clean oven",
  ],
  Office: [
    "Clean desk",
    "Organize papers",
    "Clean computer",
    "Vacuum floor",
    "Dust surfaces",
    "Clean windows",
  ],
  "Living room": [
    "Vacuum sofa",
    "Clean TV",
    "Vacuum floor",
    "Dust surfaces",
    "Clean windows",
    "Clean coffee table",
    "Organize magazines",
  ],
  Laundry: [
    "Clean washing machine",
    "Clean dryer",
    "Mop floor",
    "Clean counters",
    "Organize supplies",
  ],
  Garage: [
    "Sweep floor",
    "Organize tools",
    "Clean workbench",
    "Clean storage",
    "Clean car",
  ],
  Garden: [
    "Mow lawn",
    "Water plants",
    "Clean patio",
    "Trim bushes",
    "Clean garden tools",
  ],
  House: [
    "Clean windows",
    "Clean doors",
    "Check smoke detectors",
    "Clean air filters",
    "Clean gutters",
  ],
  Custom: ["Dust surfaces", "Clean windows", "Vacuum floor", "Organize items"],
} as const;
